apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  labels:
    app: apache
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: apache
    type: LoadBalancer
